name: npm-publish
on:
  push:
    branches:
      - main # Change this to your default branch
jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: generate-changelog
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm run build
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
